# Path to files on server
path: /

# Speed of the video processing for the ffmpeg (slow, medium, fast, veryfast)
speed: veryfast

# Formats of the video files
formats:
  # Input formats accepted
  inputs:
    - "mkv"
    - "3gp"
    - "avi"
    - "m4v"
    - "mov"
    - "mp4"
    - "mpg"
    - "mts"
    - "ogm"
  # Processed suffix is the marker that the file is already processed
  processed_suffix: processed
  # Output format
  output: mp4

# FTP settings
ftp:
  # FTP server address (without ftp://)
  address:
  # FTP username
  username:
  # FTP password
  password:
